version: '3'
services:
    jupyterhub:
        build: .
        image: jupyterhub-new:1.0
        ports:
            - "8000:8000"
        volumes:
            - jupyterhub-user-data:/home

volumes:
    jupyterhub-user-data:
