version: '3'
services:
    jupyterhub:
        build: .
        image: jupyterhub-new:1.1
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - jupyterhub-user-data:/home
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]

volumes:
    jupyterhub-user-data:
